//#line 2 "/opt/mrtros/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the obstacle_detection_ros_tool package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __obstacle_detection_ros_tool__OBSTACLEDETECTIONCONFIG_H__
#define __obstacle_detection_ros_tool__OBSTACLEDETECTIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace obstacle_detection_ros_tool
{
  class ObstacleDetectionConfigStatics;

  class ObstacleDetectionConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(ObstacleDetectionConfig &config, const ObstacleDetectionConfig &max, const ObstacleDetectionConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ObstacleDetectionConfig &config1, const ObstacleDetectionConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ObstacleDetectionConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ObstacleDetectionConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ObstacleDetectionConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ObstacleDetectionConfig &config) const = 0;
      virtual void getValue(const ObstacleDetectionConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ObstacleDetectionConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (ObstacleDetectionConfig::* field);

      virtual void clamp(ObstacleDetectionConfig &config, const ObstacleDetectionConfig &max, const ObstacleDetectionConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ObstacleDetectionConfig &config1, const ObstacleDetectionConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ObstacleDetectionConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ObstacleDetectionConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ObstacleDetectionConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ObstacleDetectionConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ObstacleDetectionConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ObstacleDetectionConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ObstacleDetectionConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ObstacleDetectionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("verbosity"==(*_i)->name){verbosity = boost::any_cast<std::string>(val);}
        if("queue_size"==(*_i)->name){queue_size = boost::any_cast<int>(val);}
        if("dummy"==(*_i)->name){dummy = boost::any_cast<double>(val);}
      }
    }

    std::string verbosity;
int queue_size;
double dummy;

    bool state;
    std::string name;

    class FRAMES
{
  public:
    FRAMES()
    {
      state = true;
      name = "Frames";
    }

    void setParams(ObstacleDetectionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    
}frames;

class PUBLISHER_AND_SUBSCRIBER
{
  public:
    PUBLISHER_AND_SUBSCRIBER()
    {
      state = true;
      name = "Publisher_and_subscriber";
    }

    void setParams(ObstacleDetectionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    
}publisher_and_subscriber;

}groups;



//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string verbosity;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double dummy;
//#line 228 "/opt/mrtros/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ObstacleDetectionConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ObstacleDetectionConfig &__max__ = __getMax__();
      const ObstacleDetectionConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ObstacleDetectionConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ObstacleDetectionConfig &__getDefault__();
    static const ObstacleDetectionConfig &__getMax__();
    static const ObstacleDetectionConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ObstacleDetectionConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ObstacleDetectionConfig::ParamDescription<std::string>::clamp(ObstacleDetectionConfig &config, const ObstacleDetectionConfig &max, const ObstacleDetectionConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ObstacleDetectionConfigStatics
  {
    friend class ObstacleDetectionConfig;

    ObstacleDetectionConfigStatics()
    {
ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT, ObstacleDetectionConfig> Default("Default", "", 0, 0, true, &ObstacleDetectionConfig::groups);
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.verbosity = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.verbosity = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.verbosity = "info";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ObstacleDetectionConfig::AbstractParamDescriptionConstPtr(new ObstacleDetectionConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &ObstacleDetectionConfig::verbosity)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ObstacleDetectionConfig::AbstractParamDescriptionConstPtr(new ObstacleDetectionConfig::ParamDescription<std::string>("verbosity", "str", 0, "Sets the verbosity for this node", "{'enum_description': 'Sets the verbosity for this node', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'debug', 'ctype': 'std::string', 'type': 'str', 'name': 'debug'}, {'srcline': 16, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'info', 'ctype': 'std::string', 'type': 'str', 'name': 'info'}, {'srcline': 17, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'warning', 'ctype': 'std::string', 'type': 'str', 'name': 'warning'}, {'srcline': 18, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'error', 'ctype': 'std::string', 'type': 'str', 'name': 'error'}, {'srcline': 19, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg', 'cconsttype': 'const char * const', 'value': 'fatal', 'ctype': 'std::string', 'type': 'str', 'name': 'fatal'}]}", &ObstacleDetectionConfig::verbosity)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.queue_size = 100;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.queue_size = 15;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ObstacleDetectionConfig::AbstractParamDescriptionConstPtr(new ObstacleDetectionConfig::ParamDescription<int>("queue_size", "int", 0, "queue size", "", &ObstacleDetectionConfig::queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ObstacleDetectionConfig::AbstractParamDescriptionConstPtr(new ObstacleDetectionConfig::ParamDescription<int>("queue_size", "int", 0, "queue size", "", &ObstacleDetectionConfig::queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.dummy = 0.0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.dummy = 1.0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.dummy = 0.1;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ObstacleDetectionConfig::AbstractParamDescriptionConstPtr(new ObstacleDetectionConfig::ParamDescription<double>("dummy", "double", 0, "My Dummy Parameter", "", &ObstacleDetectionConfig::dummy)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ObstacleDetectionConfig::AbstractParamDescriptionConstPtr(new ObstacleDetectionConfig::ParamDescription<double>("dummy", "double", 0, "My Dummy Parameter", "", &ObstacleDetectionConfig::dummy)));
ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT::FRAMES, ObstacleDetectionConfig::DEFAULT> Frames("Frames", "", 0, 1, true, &ObstacleDetectionConfig::DEFAULT::frames);
//#line 124 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Frames.convertParams();
//#line 124 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr(new ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT::FRAMES, ObstacleDetectionConfig::DEFAULT>(Frames)));
//#line 124 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr(new ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT::FRAMES, ObstacleDetectionConfig::DEFAULT>(Frames)));
ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, ObstacleDetectionConfig::DEFAULT> Publisher_and_subscriber("Publisher_and_subscriber", "", 0, 2, true, &ObstacleDetectionConfig::DEFAULT::publisher_and_subscriber);
//#line 124 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Publisher_and_subscriber.convertParams();
//#line 124 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr(new ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, ObstacleDetectionConfig::DEFAULT>(Publisher_and_subscriber)));
//#line 124 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr(new ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT::PUBLISHER_AND_SUBSCRIBER, ObstacleDetectionConfig::DEFAULT>(Publisher_and_subscriber)));
//#line 246 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr(new ObstacleDetectionConfig::GroupDescription<ObstacleDetectionConfig::DEFAULT, ObstacleDetectionConfig>(Default)));
//#line 366 "/opt/mrtros/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ObstacleDetectionConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ObstacleDetectionConfig __max__;
    ObstacleDetectionConfig __min__;
    ObstacleDetectionConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ObstacleDetectionConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ObstacleDetectionConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ObstacleDetectionConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ObstacleDetectionConfig &ObstacleDetectionConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ObstacleDetectionConfig &ObstacleDetectionConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ObstacleDetectionConfig &ObstacleDetectionConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ObstacleDetectionConfig::AbstractParamDescriptionConstPtr> &ObstacleDetectionConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ObstacleDetectionConfig::AbstractGroupDescriptionConstPtr> &ObstacleDetectionConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ObstacleDetectionConfigStatics *ObstacleDetectionConfig::__get_statics__()
  {
    const static ObstacleDetectionConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ObstacleDetectionConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg"
      const char * const ObstacleDetection_debug = "debug";
//#line 16 "/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg"
      const char * const ObstacleDetection_info = "info";
//#line 17 "/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg"
      const char * const ObstacleDetection_warning = "warning";
//#line 18 "/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg"
      const char * const ObstacleDetection_error = "error";
//#line 19 "/home/kal5-2/rammbo/devel/.private/obstacle_detection_ros_tool/share/obstacle_detection_ros_tool/cfg/ObstacleDetection.cfg"
      const char * const ObstacleDetection_fatal = "fatal";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __OBSTACLEDETECTIONRECONFIGURATOR_H__
