(cl:defpackage automated_driving_msgs-msg
  (:use )
  (:export
   "<ADDITIONALHEADERFORCOMMUNICATION>"
   "ADDITIONALHEADERFORCOMMUNICATION"
   "<BASICSAFETYMESSAGE>"
   "BASICSAFETYMESSAGE"
   "<CLASSWITHPROBABILITY>"
   "CLASSWITHPROBABILITY"
   "<DELTAPOSEWITHDELTATIME>"
   "DELTAPOSEWITHDELTATIME"
   "<DELTATRAJECTORY>"
   "DELTATRAJECTORY"
   "<MOTIONPREDICTION>"
   "MOTIONPREDICTION"
   "<MOTIONSTATE>"
   "MOTIONSTATE"
   "<OBJECTCLASSIFICATION>"
   "OBJECTCLASSIFICATION"
   "<OBJECTSTATE>"
   "OBJECTSTATE"
   "<OBJECTSTATEARRAY>"
   "OBJECTSTATEARRAY"
   "<STAMPEDFLOAT64>"
   "STAMPEDFLOAT64"
   "<TRAJECTORY>"
   "TRAJECTORY"
  ))

