# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from automated_driving_msgs/DeltaPoseWithDeltaTime.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy

class DeltaPoseWithDeltaTime(genpy.Message):
  _md5sum = "bd491e1e86421bdc854fe78f7237bf17"
  _type = "automated_driving_msgs/DeltaPoseWithDeltaTime"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Message for a desired position of an object
# License: BSD

# Time Delta, after which the position is to be reached
#    For further details: http://wiki.ros.org/std_msgs
duration delta_time

# The Position Delta to be reached
#    This delta is always relative to the current position and orientation of the object
#    For further details: http://docs.ros.org/api/geometry_msgs/html/msg/Pose.html
geometry_msgs/Pose delta_pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['delta_time','delta_pose']
  _slot_types = ['duration','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       delta_time,delta_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DeltaPoseWithDeltaTime, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.delta_time is None:
        self.delta_time = genpy.Duration()
      if self.delta_pose is None:
        self.delta_pose = geometry_msgs.msg.Pose()
    else:
      self.delta_time = genpy.Duration()
      self.delta_pose = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i7d().pack(_x.delta_time.secs, _x.delta_time.nsecs, _x.delta_pose.position.x, _x.delta_pose.position.y, _x.delta_pose.position.z, _x.delta_pose.orientation.x, _x.delta_pose.orientation.y, _x.delta_pose.orientation.z, _x.delta_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.delta_time is None:
        self.delta_time = genpy.Duration()
      if self.delta_pose is None:
        self.delta_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.delta_time.secs, _x.delta_time.nsecs, _x.delta_pose.position.x, _x.delta_pose.position.y, _x.delta_pose.position.z, _x.delta_pose.orientation.x, _x.delta_pose.orientation.y, _x.delta_pose.orientation.z, _x.delta_pose.orientation.w,) = _get_struct_2i7d().unpack(str[start:end])
      self.delta_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i7d().pack(_x.delta_time.secs, _x.delta_time.nsecs, _x.delta_pose.position.x, _x.delta_pose.position.y, _x.delta_pose.position.z, _x.delta_pose.orientation.x, _x.delta_pose.orientation.y, _x.delta_pose.orientation.z, _x.delta_pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.delta_time is None:
        self.delta_time = genpy.Duration()
      if self.delta_pose is None:
        self.delta_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 64
      (_x.delta_time.secs, _x.delta_time.nsecs, _x.delta_pose.position.x, _x.delta_pose.position.y, _x.delta_pose.position.z, _x.delta_pose.orientation.x, _x.delta_pose.orientation.y, _x.delta_pose.orientation.z, _x.delta_pose.orientation.w,) = _get_struct_2i7d().unpack(str[start:end])
      self.delta_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i7d = None
def _get_struct_2i7d():
    global _struct_2i7d
    if _struct_2i7d is None:
        _struct_2i7d = struct.Struct("<2i7d")
    return _struct_2i7d
