//#line 2 "/opt/mrtros/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the rosinterface_handler package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __rosinterface_handler__DEFAULTSCONFIG_H__
#define __rosinterface_handler__DEFAULTSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace rosinterface_handler
{
  class DefaultsConfigStatics;

  class DefaultsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(DefaultsConfig &config, const DefaultsConfig &max, const DefaultsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const DefaultsConfig &config1, const DefaultsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, DefaultsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const DefaultsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DefaultsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const DefaultsConfig &config) const = 0;
      virtual void getValue(const DefaultsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T DefaultsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (DefaultsConfig::* field);

      virtual void clamp(DefaultsConfig &config, const DefaultsConfig &max, const DefaultsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const DefaultsConfig &config1, const DefaultsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, DefaultsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const DefaultsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DefaultsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const DefaultsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const DefaultsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, DefaultsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, DefaultsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<DefaultsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(DefaultsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("int_param_w_default"==(*_i)->name){int_param_w_default = boost::any_cast<int>(val);}
        if("enum_int_param_w_default"==(*_i)->name){enum_int_param_w_default = boost::any_cast<int>(val);}
        if("enum_str_param_w_default"==(*_i)->name){enum_str_param_w_default = boost::any_cast<std::string>(val);}
        if("subscriber_w_default_topic"==(*_i)->name){subscriber_w_default_topic = boost::any_cast<std::string>(val);}
        if("subscriber_w_default_queue_size"==(*_i)->name){subscriber_w_default_queue_size = boost::any_cast<int>(val);}
        if("subscriber_diag_w_default_topic"==(*_i)->name){subscriber_diag_w_default_topic = boost::any_cast<std::string>(val);}
        if("subscriber_diag_w_default_queue_size"==(*_i)->name){subscriber_diag_w_default_queue_size = boost::any_cast<int>(val);}
        if("subscriber_diag_w_default_min_frequency"==(*_i)->name){subscriber_diag_w_default_min_frequency = boost::any_cast<double>(val);}
        if("subscriber_diag_w_default_max_delay"==(*_i)->name){subscriber_diag_w_default_max_delay = boost::any_cast<double>(val);}
        if("subscriber_public_w_default_topic"==(*_i)->name){subscriber_public_w_default_topic = boost::any_cast<std::string>(val);}
        if("subscriber_public_w_default_queue_size"==(*_i)->name){subscriber_public_w_default_queue_size = boost::any_cast<int>(val);}
        if("subscriber_global_w_default_topic"==(*_i)->name){subscriber_global_w_default_topic = boost::any_cast<std::string>(val);}
        if("subscriber_global_w_default_queue_size"==(*_i)->name){subscriber_global_w_default_queue_size = boost::any_cast<int>(val);}
        if("publisher_w_default_topic"==(*_i)->name){publisher_w_default_topic = boost::any_cast<std::string>(val);}
        if("publisher_w_default_queue_size"==(*_i)->name){publisher_w_default_queue_size = boost::any_cast<int>(val);}
        if("publisher_diag_w_default_topic"==(*_i)->name){publisher_diag_w_default_topic = boost::any_cast<std::string>(val);}
        if("publisher_diag_w_default_queue_size"==(*_i)->name){publisher_diag_w_default_queue_size = boost::any_cast<int>(val);}
        if("publisher_diag_w_default_min_frequency"==(*_i)->name){publisher_diag_w_default_min_frequency = boost::any_cast<double>(val);}
        if("publisher_diag_w_default_max_delay"==(*_i)->name){publisher_diag_w_default_max_delay = boost::any_cast<double>(val);}
        if("publisher_public_w_default_topic"==(*_i)->name){publisher_public_w_default_topic = boost::any_cast<std::string>(val);}
        if("publisher_public_w_default_queue_size"==(*_i)->name){publisher_public_w_default_queue_size = boost::any_cast<int>(val);}
        if("publisher_global_w_default_topic"==(*_i)->name){publisher_global_w_default_topic = boost::any_cast<std::string>(val);}
        if("publisher_global_w_default_queue_size"==(*_i)->name){publisher_global_w_default_queue_size = boost::any_cast<int>(val);}
      }
    }

    int int_param_w_default;
int enum_int_param_w_default;
std::string enum_str_param_w_default;
std::string subscriber_w_default_topic;
int subscriber_w_default_queue_size;
std::string subscriber_diag_w_default_topic;
int subscriber_diag_w_default_queue_size;
double subscriber_diag_w_default_min_frequency;
double subscriber_diag_w_default_max_delay;
std::string subscriber_public_w_default_topic;
int subscriber_public_w_default_queue_size;
std::string subscriber_global_w_default_topic;
int subscriber_global_w_default_queue_size;
std::string publisher_w_default_topic;
int publisher_w_default_queue_size;
std::string publisher_diag_w_default_topic;
int publisher_diag_w_default_queue_size;
double publisher_diag_w_default_min_frequency;
double publisher_diag_w_default_max_delay;
std::string publisher_public_w_default_topic;
int publisher_public_w_default_queue_size;
std::string publisher_global_w_default_topic;
int publisher_global_w_default_queue_size;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int int_param_w_default;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int enum_int_param_w_default;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string enum_str_param_w_default;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string subscriber_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int subscriber_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string subscriber_diag_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int subscriber_diag_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double subscriber_diag_w_default_min_frequency;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double subscriber_diag_w_default_max_delay;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string subscriber_public_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int subscriber_public_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string subscriber_global_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int subscriber_global_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string publisher_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int publisher_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string publisher_diag_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int publisher_diag_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double publisher_diag_w_default_min_frequency;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double publisher_diag_w_default_max_delay;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string publisher_public_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int publisher_public_w_default_queue_size;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string publisher_global_w_default_topic;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int publisher_global_w_default_queue_size;
//#line 228 "/opt/mrtros/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("DefaultsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const DefaultsConfig &__max__ = __getMax__();
      const DefaultsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const DefaultsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const DefaultsConfig &__getDefault__();
    static const DefaultsConfig &__getMax__();
    static const DefaultsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const DefaultsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void DefaultsConfig::ParamDescription<std::string>::clamp(DefaultsConfig &config, const DefaultsConfig &max, const DefaultsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class DefaultsConfigStatics
  {
    friend class DefaultsConfig;

    DefaultsConfigStatics()
    {
DefaultsConfig::GroupDescription<DefaultsConfig::DEFAULT, DefaultsConfig> Default("Default", "", 0, 0, true, &DefaultsConfig::groups);
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.int_param_w_default = -2147483648;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.int_param_w_default = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.int_param_w_default = 1;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("int_param_w_default", "int", 0, "An Integer parameter", "", &DefaultsConfig::int_param_w_default)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("int_param_w_default", "int", 0, "An Integer parameter", "", &DefaultsConfig::int_param_w_default)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enum_int_param_w_default = -2147483648;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enum_int_param_w_default = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enum_int_param_w_default = 1;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("enum_int_param_w_default", "int", 0, "enum", "{'enum_description': 'enum', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Small'}, {'srcline': 16, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Medium'}, {'srcline': 17, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Large'}, {'srcline': 18, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'ExtraLarge'}]}", &DefaultsConfig::enum_int_param_w_default)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("enum_int_param_w_default", "int", 0, "enum", "{'enum_description': 'enum', 'enum': [{'srcline': 15, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Small'}, {'srcline': 16, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Medium'}, {'srcline': 17, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Large'}, {'srcline': 18, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'ExtraLarge'}]}", &DefaultsConfig::enum_int_param_w_default)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enum_str_param_w_default = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enum_str_param_w_default = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enum_str_param_w_default = "One";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("enum_str_param_w_default", "str", 0, "string enum", "{'enum_description': 'string enum', 'enum': [{'srcline': 21, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'Zero', 'ctype': 'std::string', 'type': 'str', 'name': 'Zero'}, {'srcline': 22, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'One', 'ctype': 'std::string', 'type': 'str', 'name': 'One'}, {'srcline': 23, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'Two', 'ctype': 'std::string', 'type': 'str', 'name': 'Two'}, {'srcline': 24, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'Three', 'ctype': 'std::string', 'type': 'str', 'name': 'Three'}]}", &DefaultsConfig::enum_str_param_w_default)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("enum_str_param_w_default", "str", 0, "string enum", "{'enum_description': 'string enum', 'enum': [{'srcline': 21, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'Zero', 'ctype': 'std::string', 'type': 'str', 'name': 'Zero'}, {'srcline': 22, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'One', 'ctype': 'std::string', 'type': 'str', 'name': 'One'}, {'srcline': 23, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'Two', 'ctype': 'std::string', 'type': 'str', 'name': 'Two'}, {'srcline': 24, 'description': '', 'srcfile': '/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg', 'cconsttype': 'const char * const', 'value': 'Three', 'ctype': 'std::string', 'type': 'str', 'name': 'Three'}]}", &DefaultsConfig::enum_str_param_w_default)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_w_default_topic = "in_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_w_default_topic", "str", 0, "Topic for subscriber", "", &DefaultsConfig::subscriber_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_w_default_topic", "str", 0, "Topic for subscriber", "", &DefaultsConfig::subscriber_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_w_default_queue_size", "int", 0, "Queue size for subscriber", "", &DefaultsConfig::subscriber_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_w_default_queue_size", "int", 0, "Queue size for subscriber", "", &DefaultsConfig::subscriber_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_diag_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_diag_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_diag_w_default_topic = "in_point_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_diag_w_default_topic", "str", 0, "Topic for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_diag_w_default_topic", "str", 0, "Topic for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_diag_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_diag_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_diag_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_diag_w_default_queue_size", "int", 0, "Queue size for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_diag_w_default_queue_size", "int", 0, "Queue size for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_diag_w_default_min_frequency = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_diag_w_default_min_frequency = std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_diag_w_default_min_frequency = 0.0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("subscriber_diag_w_default_min_frequency", "double", 0, "Minimal message frequency for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_min_frequency)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("subscriber_diag_w_default_min_frequency", "double", 0, "Minimal message frequency for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_min_frequency)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_diag_w_default_max_delay = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_diag_w_default_max_delay = std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_diag_w_default_max_delay = 1e+308;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("subscriber_diag_w_default_max_delay", "double", 0, "Maximal delay for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_max_delay)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("subscriber_diag_w_default_max_delay", "double", 0, "Maximal delay for subscriber", "", &DefaultsConfig::subscriber_diag_w_default_max_delay)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_public_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_public_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_public_w_default_topic = "in_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_public_w_default_topic", "str", 0, "Topic for public subscriber", "", &DefaultsConfig::subscriber_public_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_public_w_default_topic", "str", 0, "Topic for public subscriber", "", &DefaultsConfig::subscriber_public_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_public_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_public_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_public_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_public_w_default_queue_size", "int", 0, "Queue size for public subscriber", "", &DefaultsConfig::subscriber_public_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_public_w_default_queue_size", "int", 0, "Queue size for public subscriber", "", &DefaultsConfig::subscriber_public_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_global_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_global_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_global_w_default_topic = "in_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_global_w_default_topic", "str", 0, "Topic for global subscriber", "", &DefaultsConfig::subscriber_global_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("subscriber_global_w_default_topic", "str", 0, "Topic for global subscriber", "", &DefaultsConfig::subscriber_global_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.subscriber_global_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.subscriber_global_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.subscriber_global_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_global_w_default_queue_size", "int", 0, "Queue size for global subscriber", "", &DefaultsConfig::subscriber_global_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("subscriber_global_w_default_queue_size", "int", 0, "Queue size for global subscriber", "", &DefaultsConfig::subscriber_global_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_w_default_topic = "out_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_w_default_topic", "str", 0, "Topic for publisher", "", &DefaultsConfig::publisher_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_w_default_topic", "str", 0, "Topic for publisher", "", &DefaultsConfig::publisher_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_w_default_queue_size", "int", 0, "Queue size for publisher", "", &DefaultsConfig::publisher_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_w_default_queue_size", "int", 0, "Queue size for publisher", "", &DefaultsConfig::publisher_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_diag_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_diag_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_diag_w_default_topic = "out_point_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_diag_w_default_topic", "str", 0, "Topic for publisher", "", &DefaultsConfig::publisher_diag_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_diag_w_default_topic", "str", 0, "Topic for publisher", "", &DefaultsConfig::publisher_diag_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_diag_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_diag_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_diag_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_diag_w_default_queue_size", "int", 0, "Queue size for publisher", "", &DefaultsConfig::publisher_diag_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_diag_w_default_queue_size", "int", 0, "Queue size for publisher", "", &DefaultsConfig::publisher_diag_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_diag_w_default_min_frequency = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_diag_w_default_min_frequency = std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_diag_w_default_min_frequency = 0.0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("publisher_diag_w_default_min_frequency", "double", 0, "Minimal message frequency for publisher", "", &DefaultsConfig::publisher_diag_w_default_min_frequency)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("publisher_diag_w_default_min_frequency", "double", 0, "Minimal message frequency for publisher", "", &DefaultsConfig::publisher_diag_w_default_min_frequency)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_diag_w_default_max_delay = -std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_diag_w_default_max_delay = std::numeric_limits<double>::infinity();
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_diag_w_default_max_delay = 1e+308;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("publisher_diag_w_default_max_delay", "double", 0, "Maximal delay for publisher", "", &DefaultsConfig::publisher_diag_w_default_max_delay)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<double>("publisher_diag_w_default_max_delay", "double", 0, "Maximal delay for publisher", "", &DefaultsConfig::publisher_diag_w_default_max_delay)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_public_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_public_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_public_w_default_topic = "out_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_public_w_default_topic", "str", 0, "Topic for public publisher", "", &DefaultsConfig::publisher_public_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_public_w_default_topic", "str", 0, "Topic for public publisher", "", &DefaultsConfig::publisher_public_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_public_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_public_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_public_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_public_w_default_queue_size", "int", 0, "Queue size for public publisher", "", &DefaultsConfig::publisher_public_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_public_w_default_queue_size", "int", 0, "Queue size for public publisher", "", &DefaultsConfig::publisher_public_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_global_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_global_w_default_topic = "";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_global_w_default_topic = "out_topic";
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_global_w_default_topic", "str", 0, "Topic for global publisher", "", &DefaultsConfig::publisher_global_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<std::string>("publisher_global_w_default_topic", "str", 0, "Topic for global publisher", "", &DefaultsConfig::publisher_global_w_default_topic)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.publisher_global_w_default_queue_size = 0;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.publisher_global_w_default_queue_size = 2147483647;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.publisher_global_w_default_queue_size = 5;
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_global_w_default_queue_size", "int", 0, "Queue size for global publisher", "", &DefaultsConfig::publisher_global_w_default_queue_size)));
//#line 291 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DefaultsConfig::AbstractParamDescriptionConstPtr(new DefaultsConfig::ParamDescription<int>("publisher_global_w_default_queue_size", "int", 0, "Queue size for global publisher", "", &DefaultsConfig::publisher_global_w_default_queue_size)));
//#line 246 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/mrtros/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(DefaultsConfig::AbstractGroupDescriptionConstPtr(new DefaultsConfig::GroupDescription<DefaultsConfig::DEFAULT, DefaultsConfig>(Default)));
//#line 366 "/opt/mrtros/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<DefaultsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<DefaultsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<DefaultsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    DefaultsConfig __max__;
    DefaultsConfig __min__;
    DefaultsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const DefaultsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static DefaultsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &DefaultsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const DefaultsConfig &DefaultsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const DefaultsConfig &DefaultsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const DefaultsConfig &DefaultsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<DefaultsConfig::AbstractParamDescriptionConstPtr> &DefaultsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<DefaultsConfig::AbstractGroupDescriptionConstPtr> &DefaultsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const DefaultsConfigStatics *DefaultsConfig::__get_statics__()
  {
    const static DefaultsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = DefaultsConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const int Defaults_Small = 0;
//#line 16 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const int Defaults_Medium = 1;
//#line 17 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const int Defaults_Large = 2;
//#line 18 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const int Defaults_ExtraLarge = 3;
//#line 21 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const char * const Defaults_Zero = "Zero";
//#line 22 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const char * const Defaults_One = "One";
//#line 23 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const char * const Defaults_Two = "Two";
//#line 24 "/home/kal5-2/rammbo/devel/.private/rosinterface_handler/share/rosinterface_handler/cfg/Defaults.cfg"
      const char * const Defaults_Three = "Three";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DEFAULTSRECONFIGURATOR_H__
