// Generated by gencpp from file automated_driving_msgs/ClassWithProbability.msg
// DO NOT EDIT!


#ifndef AUTOMATED_DRIVING_MSGS_MESSAGE_CLASSWITHPROBABILITY_H
#define AUTOMATED_DRIVING_MSGS_MESSAGE_CLASSWITHPROBABILITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace automated_driving_msgs
{
template <class ContainerAllocator>
struct ClassWithProbability_
{
  typedef ClassWithProbability_<ContainerAllocator> Type;

  ClassWithProbability_()
    : classification(0)
    , probability(0.0)  {
    }
  ClassWithProbability_(const ContainerAllocator& _alloc)
    : classification(0)
    , probability(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _classification_type;
  _classification_type classification;

   typedef float _probability_type;
  _probability_type probability;





  typedef boost::shared_ptr< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> const> ConstPtr;

}; // struct ClassWithProbability_

typedef ::automated_driving_msgs::ClassWithProbability_<std::allocator<void> > ClassWithProbability;

typedef boost::shared_ptr< ::automated_driving_msgs::ClassWithProbability > ClassWithProbabilityPtr;
typedef boost::shared_ptr< ::automated_driving_msgs::ClassWithProbability const> ClassWithProbabilityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace automated_driving_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/mrtros/share/std_msgs/cmake/../msg'], 'automated_driving_msgs': ['/home/kal5-2/rammbo/src/automated_driving_msgs/msg'], 'shape_msgs': ['/opt/mrtros/share/shape_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/mrtros/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "597d4d46d4c71549dc3712237b4f7830";
  }

  static const char* value(const ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x597d4d46d4c71549ULL;
  static const uint64_t static_value2 = 0xdc3712237b4f7830ULL;
};

template<class ContainerAllocator>
struct DataType< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automated_driving_msgs/ClassWithProbability";
  }

  static const char* value(const ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# One class with its respective probability\n"
"# License: BSD\n"
"\n"
"uint8 classification\n"
"\n"
"# Class probability\n"
"#    Range: [0, 1]\n"
"float32 probability\n"
;
  }

  static const char* value(const ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.classification);
      stream.next(m.probability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassWithProbability_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automated_driving_msgs::ClassWithProbability_<ContainerAllocator>& v)
  {
    s << indent << "classification: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.classification);
    s << indent << "probability: ";
    Printer<float>::stream(s, indent + "  ", v.probability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMATED_DRIVING_MSGS_MESSAGE_CLASSWITHPROBABILITY_H
