// Generated by gencpp from file automated_driving_msgs/DeltaTrajectory.msg
// DO NOT EDIT!


#ifndef AUTOMATED_DRIVING_MSGS_MESSAGE_DELTATRAJECTORY_H
#define AUTOMATED_DRIVING_MSGS_MESSAGE_DELTATRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <automated_driving_msgs/DeltaPoseWithDeltaTime.h>

namespace automated_driving_msgs
{
template <class ContainerAllocator>
struct DeltaTrajectory_
{
  typedef DeltaTrajectory_<ContainerAllocator> Type;

  DeltaTrajectory_()
    : header()
    , delta_poses_with_delta_time()  {
    }
  DeltaTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , delta_poses_with_delta_time(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >::other >  _delta_poses_with_delta_time_type;
  _delta_poses_with_delta_time_type delta_poses_with_delta_time;





  typedef boost::shared_ptr< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct DeltaTrajectory_

typedef ::automated_driving_msgs::DeltaTrajectory_<std::allocator<void> > DeltaTrajectory;

typedef boost::shared_ptr< ::automated_driving_msgs::DeltaTrajectory > DeltaTrajectoryPtr;
typedef boost::shared_ptr< ::automated_driving_msgs::DeltaTrajectory const> DeltaTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace automated_driving_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/mrtros/share/std_msgs/cmake/../msg'], 'automated_driving_msgs': ['/home/kal5-2/rammbo/src/automated_driving_msgs/msg'], 'shape_msgs': ['/opt/mrtros/share/shape_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/mrtros/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326b401761a7fb398dc1c64746db2f8e";
  }

  static const char* value(const ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326b401761a7fb39ULL;
  static const uint64_t static_value2 = 0x8dc1c64746db2f8eULL;
};

template<class ContainerAllocator>
struct DataType< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automated_driving_msgs/DeltaTrajectory";
  }

  static const char* value(const ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for a desired motion of an object expressed by an array of desired positions\n"
"# License: BSD\n"
"\n"
"# Header\n"
"Header header\n"
"\n"
"# Array of desired delta positions with their respective delta time, after which the position is to be reached\n"
"DeltaPoseWithDeltaTime[] delta_poses_with_delta_time\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: automated_driving_msgs/DeltaPoseWithDeltaTime\n"
"# Message for a desired position of an object\n"
"# License: BSD\n"
"\n"
"# Time Delta, after which the position is to be reached\n"
"#    For further details: http://wiki.ros.org/std_msgs\n"
"duration delta_time\n"
"\n"
"# The Position Delta to be reached\n"
"#    This delta is always relative to the current position and orientation of the object\n"
"#    For further details: http://docs.ros.org/api/geometry_msgs/html/msg/Pose.html\n"
"geometry_msgs/Pose delta_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.delta_poses_with_delta_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeltaTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automated_driving_msgs::DeltaTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "delta_poses_with_delta_time[]" << std::endl;
    for (size_t i = 0; i < v.delta_poses_with_delta_time.size(); ++i)
    {
      s << indent << "  delta_poses_with_delta_time[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >::stream(s, indent + "    ", v.delta_poses_with_delta_time[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMATED_DRIVING_MSGS_MESSAGE_DELTATRAJECTORY_H
