// Generated by gencpp from file automated_driving_msgs/DeltaPoseWithDeltaTime.msg
// DO NOT EDIT!


#ifndef AUTOMATED_DRIVING_MSGS_MESSAGE_DELTAPOSEWITHDELTATIME_H
#define AUTOMATED_DRIVING_MSGS_MESSAGE_DELTAPOSEWITHDELTATIME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace automated_driving_msgs
{
template <class ContainerAllocator>
struct DeltaPoseWithDeltaTime_
{
  typedef DeltaPoseWithDeltaTime_<ContainerAllocator> Type;

  DeltaPoseWithDeltaTime_()
    : delta_time()
    , delta_pose()  {
    }
  DeltaPoseWithDeltaTime_(const ContainerAllocator& _alloc)
    : delta_time()
    , delta_pose(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Duration _delta_time_type;
  _delta_time_type delta_time;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _delta_pose_type;
  _delta_pose_type delta_pose;





  typedef boost::shared_ptr< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> const> ConstPtr;

}; // struct DeltaPoseWithDeltaTime_

typedef ::automated_driving_msgs::DeltaPoseWithDeltaTime_<std::allocator<void> > DeltaPoseWithDeltaTime;

typedef boost::shared_ptr< ::automated_driving_msgs::DeltaPoseWithDeltaTime > DeltaPoseWithDeltaTimePtr;
typedef boost::shared_ptr< ::automated_driving_msgs::DeltaPoseWithDeltaTime const> DeltaPoseWithDeltaTimeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace automated_driving_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/mrtros/share/std_msgs/cmake/../msg'], 'automated_driving_msgs': ['/home/kal5-2/rammbo/src/automated_driving_msgs/msg'], 'shape_msgs': ['/opt/mrtros/share/shape_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/mrtros/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd491e1e86421bdc854fe78f7237bf17";
  }

  static const char* value(const ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd491e1e86421bdcULL;
  static const uint64_t static_value2 = 0x854fe78f7237bf17ULL;
};

template<class ContainerAllocator>
struct DataType< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "automated_driving_msgs/DeltaPoseWithDeltaTime";
  }

  static const char* value(const ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for a desired position of an object\n"
"# License: BSD\n"
"\n"
"# Time Delta, after which the position is to be reached\n"
"#    For further details: http://wiki.ros.org/std_msgs\n"
"duration delta_time\n"
"\n"
"# The Position Delta to be reached\n"
"#    This delta is always relative to the current position and orientation of the object\n"
"#    For further details: http://docs.ros.org/api/geometry_msgs/html/msg/Pose.html\n"
"geometry_msgs/Pose delta_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delta_time);
      stream.next(m.delta_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeltaPoseWithDeltaTime_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::automated_driving_msgs::DeltaPoseWithDeltaTime_<ContainerAllocator>& v)
  {
    s << indent << "delta_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.delta_time);
    s << indent << "delta_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.delta_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOMATED_DRIVING_MSGS_MESSAGE_DELTAPOSEWITHDELTATIME_H
